version: "3.8"

services:

  backend:
    build: ./src/backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"

  frontend:
    build: ./src/frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
